import { PublicCapabilityCard } from './public-capability';

export const PUBLIC_CAPABILITY_SEED: PublicCapabilityCard[] = [
  // ── Sweden — Aircraft & Air Units ────────────────────────────────────────
  {
    id: 'sweden-gripen-cd',
    displayName: 'JAS 39 Gripen C/D',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/gripen-c-series',
    confidence: 'MEDIUM',
    caveat: 'Combat radius is a planning estimate; ferry range is official but varies with loadout.',
    operatorSummary: 'Single-engine multirole fighter. 8 armament stations, PS-05/A radar, Mach 2.0. Swedish air defense backbone.',
    technicalSpecs: { range: '3000km ferry', endurance: '~2.5h combat', altitude: '15240m', radarType: 'PS-05/A' },
    tags: ['Fighter', 'Sweden', 'Multirole'],
  },
  {
    id: 'sweden-gripen-e',
    displayName: 'JAS 39E Gripen',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/gripen-e-series',
    confidence: 'MEDIUM',
    caveat: 'Some specs are manufacturer claims; operational combat radius is not publicly disclosed.',
    operatorSummary: 'Next-gen multirole fighter with AESA radar, increased range, and 10 weapon stations.',
    technicalSpecs: { range: '3500km ferry', endurance: '~3.5h combat', altitude: '16000m', radarType: 'Raven ES-05 AESA' },
    tags: ['Fighter', 'Sweden', 'AESA'],
  },
  {
    id: 'sweden-s100b-argus',
    displayName: 'S 100B Argus (Erieye AEW)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'AEW&C',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/globaleye',
    confidence: 'HIGH',
    caveat: 'Public specifications only. Erieye radar range >550km per Saab.',
    operatorSummary: 'Airborne early warning and control. Erieye radar, >550km range, 11h endurance.',
    technicalSpecs: { range: '>550km', endurance: '11h', radarType: 'Erieye ER (GaN AESA)' },
    tags: ['ISR', 'AEW&C', 'Sweden'],
  },
  {
    id: 'sweden-s102d-korpen',
    displayName: 'S 102D Korpen (SIGINT)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SIGINT',
    publicSourceName: 'Swedish Armed Forces',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'SIGINT capabilities are not publicly disclosed; only existence is acknowledged.',
    operatorSummary: 'Signals intelligence aircraft based on Gulfstream platform. Limited public data.',
    technicalSpecs: { endurance: '~8h' },
    tags: ['SIGINT', 'Sweden', 'ISR'],
  },
  {
    id: 'sweden-tp84-hercules',
    displayName: 'TP 84 Hercules',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'LOGISTICS',
    mappedTwin: 'LogisticsSnapshot',
    steelAbstraction: 'TRANSPORT/TANKER',
    publicSourceName: 'Swedish Armed Forces',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Standard C-130H specs; Swedish-specific modifications not public.',
    operatorSummary: 'Tactical transport and aerial refueling. C-130H airframe, fuel offload capacity ~20,000 kg.',
    technicalSpecs: { range: '3800km', endurance: '~6h' },
    tags: ['Transport', 'Tanker', 'Sweden'],
  },
  {
    id: 'sweden-hkp16-black-hawk',
    displayName: 'Helikopter 16 (Black Hawk)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'HELICOPTER',
    publicSourceName: 'Swedish Armed Forces',
    publicSourceUrl: '',
    confidence: 'HIGH',
    caveat: 'Standard UH-60M public specs.',
    operatorSummary: 'Medium-lift utility helicopter for CSAR, MEDEVAC, and tactical transport.',
    technicalSpecs: { range: '520km', endurance: '~4h', altitude: '5700m' },
    tags: ['Helicopter', 'CSAR', 'Sweden'],
  },
  {
    id: 'sweden-hkp14-nh90',
    displayName: 'Helikopter 14 (NH90)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'HELICOPTER',
    publicSourceName: 'Swedish Armed Forces',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Corrected: Hkp 14 is NH90, not Hkp 15 (which is A109).',
    operatorSummary: 'ASW/transport helicopter. Naval variant for anti-submarine warfare and SAR.',
    technicalSpecs: { range: '800km', endurance: '~5h', altitude: '6000m' },
    tags: ['Helicopter', 'ASW', 'Sweden'],
  },

  // ── Sweden — GBAD ───────────────────────────────────────────────────────
  {
    id: 'sweden-bamse',
    displayName: 'RBS 23 BAMSE',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'GBAD',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'SHORAD/MRAD',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/bamse',
    confidence: 'MEDIUM',
    caveat: 'Range is OSINT estimate. Pk values are test-condition estimates.',
    operatorSummary: 'Medium-range air defense system. ~25km engagement range, concurrent multi-target engagement.',
    technicalSpecs: { range: '~25km', altitude: '~15km', radarType: 'Giraffe AMB' },
    tags: ['SAM', 'Sweden', 'SHORAD'],
  },
  {
    id: 'sweden-rbs70-ng',
    displayName: 'Saab RBS 70 NG',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'EFFECTOR',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'VSHORAD',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/rbs-70-ng',
    confidence: 'HIGH',
    caveat: 'Requires laser beam-riding guidance.',
    operatorSummary: 'Very short-range air defense system with un-jammable laser guidance. >9km range.',
    technicalSpecs: { range: '>9km', radarType: 'Laser beam-riding' },
    tags: ['Missile', 'VSHORAD', 'Sweden'],
  },
  {
    id: 'sweden-iris-t-sls',
    displayName: 'IRIS-T SLS (RBS 98)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'EFFECTOR',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'SHORAD',
    publicSourceName: 'Diehl Defence / Swedish Armed Forces',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range ~25km from public sources. Pk values not credibly public.',
    operatorSummary: 'Short-range air defense based on IRIS-T missile. Fire-and-forget, all-weather capable.',
    technicalSpecs: { range: '~25km', altitude: '~10km' },
    tags: ['SAM', 'SHORAD', 'Sweden'],
  },
  {
    id: 'sweden-patriot-pac3',
    displayName: 'Patriot PAC-3 MSE (Lv 103)',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'GBAD',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'LONG RANGE SAM',
    publicSourceName: 'NATO / Swedish Armed Forces',
    publicSourceUrl: 'https://www.nato.int/cps/en/natohq/topics_8206.htm',
    confidence: 'HIGH',
    caveat: 'Swedish designation Lv 103. Range ~160km. Pk values are test-condition estimates.',
    operatorSummary: 'Long-range air and missile defense. AN/MPQ-65 radar, MSE missile, ~160km range.',
    technicalSpecs: { range: '~160km', altitude: '~24km', radarType: 'AN/MPQ-65 AESA' },
    tags: ['NATO', 'PAC-3', 'Air Defense', 'Sweden'],
  },
  {
    id: 'sweden-rbs15f-coastal',
    displayName: 'RBS-15F / RBS15 Mk3/Mk4',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'EFFECTOR',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'ANTI-SHIP MISSILE',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/rbs-15',
    confidence: 'MEDIUM',
    caveat: 'RBS 15F is air-launched (Gripen). Land/coastal variants are RBS 15KA/Mk3/Mk4 Gungnir.',
    operatorSummary: 'Anti-ship missile family. Air-launched (F) and coastal (KA/Mk3/Mk4) variants. Range >200km.',
    technicalSpecs: { range: '>200km' },
    tags: ['Anti-ship', 'Sweden', 'Coastal'],
  },

  // ── Sweden — Sensors ────────────────────────────────────────────────────
  {
    id: 'sweden-giraffe-amb',
    displayName: 'Saab Giraffe AMB',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'SENSOR',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'GBAD SENSOR',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/giraffe-amb',
    confidence: 'HIGH',
    caveat: 'Public range claim ~120km against fighter-sized targets.',
    operatorSummary: 'Multi-beam 3D surveillance radar. ~120km fighter range, simultaneous multi-target tracking.',
    technicalSpecs: { range: '~120km', radarType: 'G/H-band multi-beam' },
    tags: ['Radar', 'GBAD', 'Sweden'],
  },
  {
    id: 'sweden-ps860-hard',
    displayName: 'PS-860 (HARD)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'SENSOR',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'GBAD SENSOR',
    publicSourceName: 'Swedish Armed Forces',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range and performance are OSINT estimates.',
    operatorSummary: 'Helicopter and aircraft radar detector. ~210km range, used for air surveillance.',
    technicalSpecs: { range: '~210km' },
    tags: ['Radar', 'Sweden', 'Surveillance'],
  },
  {
    id: 'sweden-ps05a-gripen',
    displayName: 'PS-05/A (Gripen Radar)',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'SENSOR',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'FIGHTER RADAR',
    publicSourceName: 'Saab / Ericsson',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Fighter radar ranges are not credibly public.',
    operatorSummary: 'Gripen C/D multi-mode radar. Range not credibly public; estimated ~150km against fighter.',
    technicalSpecs: { range: '~150km (OSINT)', radarType: 'PS-05/A' },
    tags: ['Fighter radar', 'Sweden', 'Gripen'],
  },
  {
    id: 'sweden-eribeye-aew',
    displayName: 'Erieye AEW Radar',
    side: 'BLUE',
    layer: 'SWEDEN_SAAB_PUBLIC',
    category: 'SENSOR',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'AEW RADAR',
    publicSourceName: 'Saab Official',
    publicSourceUrl: 'https://www.saab.com/products/globaleye',
    confidence: 'HIGH',
    caveat: 'Public range claim >550km for large targets.',
    operatorSummary: 'Airborne AESA radar for AEW&C. >550km range against large targets, 360° coverage.',
    technicalSpecs: { range: '>550km', radarType: 'Erieye ER GaN AESA' },
    tags: ['AEW', 'Sweden', 'AESA'],
  },

  // ── NATO ────────────────────────────────────────────────────────────────
  {
    id: 'nato-f35',
    displayName: 'F-35A/B Lightning II',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'USAF / Lockheed Martin',
    publicSourceUrl: 'https://www.lockheedmartin.com/en-us/products/f35.html',
    confidence: 'MEDIUM',
    caveat: 'Range and combat radius are public estimates; classified performance is not included.',
    operatorSummary: '5th-gen stealth multirole fighter. ~1,093km combat radius (A model), internal weapon bays.',
    technicalSpecs: { range: '~2,200km ferry', endurance: '~2.5h combat', altitude: '15,240m', radarType: 'AN/APG-81 AESA' },
    tags: ['NATO', 'F-35', 'Stealth'],
  },
  {
    id: 'nato-f16',
    displayName: 'F-16 Fighting Falcon',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'USAF / Lockheed Martin',
    publicSourceUrl: 'https://www.lockheedmartin.com/en-us/products/f-16.html',
    confidence: 'HIGH',
    caveat: 'Well-documented public specs.',
    operatorSummary: '4th-gen multirole fighter. ~550km combat radius, Mach 2.0. Widely deployed across NATO.',
    technicalSpecs: { range: '~4,000km ferry', altitude: '15,240m', radarType: 'AN/APG-83 SABR AESA' },
    tags: ['NATO', 'F-16', 'Multirole'],
  },
  {
    id: 'nato-eurofighter',
    displayName: 'Eurofighter Typhoon',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'AIRCRAFT',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'Eurofighter GmbH',
    publicSourceUrl: 'https://www.eurofighter.com/',
    confidence: 'MEDIUM',
    caveat: 'Public performance estimates.',
    operatorSummary: '4.5-gen canard-delta multirole fighter. ~1,390km combat radius, Mach 2.0.',
    technicalSpecs: { range: '~2,900km ferry', altitude: '19,812m', radarType: 'Captor-E AESA' },
    tags: ['NATO', 'Eurofighter', 'Air Superiority'],
  },
  {
    id: 'nato-e3-sentry',
    displayName: 'E-3 Sentry AWACS',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'AEW&C',
    publicSourceName: 'NATO',
    publicSourceUrl: 'https://www.nato.int/cps/en/natohq/topics_8206.htm',
    confidence: 'HIGH',
    caveat: 'Public range claim ~400km.',
    operatorSummary: 'Airborne warning and control system. AN/APY-2 radar, ~400km range, 8h endurance.',
    technicalSpecs: { range: '~400km', endurance: '8h', radarType: 'AN/APY-2' },
    tags: ['NATO', 'AEW&C', 'C2'],
  },
  {
    id: 'nato-rc135',
    displayName: 'RC-135 Rivet Joint',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SIGINT',
    publicSourceName: 'USAF',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'SIGINT capabilities are classified; only existence and platform specs are public.',
    operatorSummary: 'Signals intelligence aircraft. Sensor suite classified, loiter time ~10h.',
    technicalSpecs: { range: '~5,500km', endurance: '~10h' },
    tags: ['NATO', 'SIGINT', 'ISR'],
  },
  {
    id: 'nato-patriot-pac3-mse',
    displayName: 'Patriot PAC-3 MSE',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'GBAD',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'LONG RANGE SAM',
    publicSourceName: 'NATO / Raytheon',
    publicSourceUrl: 'https://www.raytheon.com/capabilities/patriot',
    confidence: 'HIGH',
    caveat: 'NATO standard capability model. Pk values are test-condition estimates.',
    operatorSummary: 'Advanced tactical air and missile defense. ~160km range, AN/MPQ-65 radar.',
    technicalSpecs: { range: '~160km', altitude: '~24km', radarType: 'AN/MPQ-65 AESA' },
    tags: ['NATO', 'PAC-3', 'Air Defense'],
  },
  {
    id: 'nato-nasams',
    displayName: 'NASAMS',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'GBAD',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MRAD',
    publicSourceName: 'Kongsberg / Raytheon',
    publicSourceUrl: 'https://www.kongsberg.com/nasams',
    confidence: 'HIGH',
    caveat: 'Public range ~25-50km.',
    operatorSummary: 'Medium-range air defense system using AIM-120 AMRAAM and IRIS-T missiles.',
    technicalSpecs: { range: '~25-50km', radarType: 'MPQ-64 Sentinel' },
    tags: ['NATO', 'NASAMS', 'Air Defense'],
  },
  {
    id: 'nato-iris-t-slm',
    displayName: 'IRIS-T SLM',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'GBAD',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MRAD',
    publicSourceName: 'Diehl Defence',
    publicSourceUrl: 'https://www.diehl.com/defence/',
    confidence: 'MEDIUM',
    caveat: 'Range is manufacturer claim.',
    operatorSummary: 'Medium-range air defense. ~40km range, all-weather, fire-and-forget.',
    technicalSpecs: { range: '~40km', altitude: '~20km' },
    tags: ['NATO', 'IRIS-T', 'Air Defense'],
  },
  {
    id: 'nato-camm-er',
    displayName: 'CAMM-ER',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'GBAD',
    mappedTwin: 'BaseTwin',
    steelAbstraction: 'MRAD',
    publicSourceName: 'MBDA / UK MoD',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range is manufacturer claim.',
    operatorSummary: 'Common Anti-Air Modular Missile – Extended Range. ~45km, active radar homing.',
    technicalSpecs: { range: '~45km', altitude: '~10km' },
    tags: ['NATO', 'CAMM', 'Air Defense'],
  },
  {
    id: 'nato-arleigh-burke',
    displayName: 'Arleigh Burke-class Destroyer',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'LOGISTICS',
    mappedTwin: 'LogisticsSnapshot',
    steelAbstraction: 'DESTROYER',
    publicSourceName: 'US Navy',
    publicSourceUrl: '',
    confidence: 'HIGH',
    caveat: 'Standard public specs.',
    operatorSummary: 'Guided-missile destroyer. 96 VLS cells, Aegis combat system, SM-2/3/6, Tomahawk.',
    technicalSpecs: { range: '8,400km at 20kn' },
    tags: ['NATO', 'Destroyer', 'Aegis'],
  },
  {
    id: 'nato-type26-frigate',
    displayName: 'Type 26 Frigate (City-class)',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'LOGISTICS',
    mappedTwin: 'LogisticsSnapshot',
    steelAbstraction: 'FRIGATE',
    publicSourceName: 'Royal Navy',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Public design specs.',
    operatorSummary: 'Anti-submarine warfare frigate. 24 VLS cells, Sea Ceptor (CAMM), ~13,000km range.',
    technicalSpecs: { range: '~13,000km' },
    tags: ['NATO', 'Frigate', 'ASW'],
  },
  {
    id: 'nato-f125-baden',
    displayName: 'F 125 Baden-Württemberg',
    side: 'BLUE',
    layer: 'NATO_PUBLIC',
    category: 'LOGISTICS',
    mappedTwin: 'LogisticsSnapshot',
    steelAbstraction: 'FRIGATE',
    publicSourceName: 'German Navy',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Public design specs.',
    operatorSummary: 'German air-defense frigate. SM-2, ESSM, ~4,000nm range.',
    technicalSpecs: { range: '~7,400km' },
    tags: ['NATO', 'Frigate', 'Germany'],
  },

  // ── Russia — Aircraft ───────────────────────────────────────────────────
  {
    id: 'russia-su35',
    displayName: 'Su-35S Flanker-E',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'OSINT / UAC',
    publicSourceUrl: 'https://en.wikipedia.org/wiki/Sukhoi_Su-35',
    confidence: 'MEDIUM',
    caveat: 'Performance figures are manufacturer/OSINT estimates.',
    operatorSummary: '4++ gen heavy fighter. Mach 2.25, ~1,600km combat radius, 12 weapon stations.',
    technicalSpecs: { range: '~3,600km ferry', endurance: '~3.5h combat', altitude: '18,000m', radarType: 'Irbis-E PESA' },
    tags: ['Russia', 'Fighter', 'Flanker'],
  },
  {
    id: 'russia-su34',
    displayName: 'Su-34 Fullback',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'STRIKE FIGHTER',
    publicSourceName: 'OSINT / UAC',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Combat radius is OSINT estimate.',
    operatorSummary: 'Twin-seat strike fighter. ~1,100km combat radius, Kh-31/Kh-59 missile capability.',
    technicalSpecs: { range: '~4,000km ferry', altitude: '15,000m', radarType: 'V004 Sh141 PESA' },
    tags: ['Russia', 'Strike', 'Fullback'],
  },
  {
    id: 'russia-mig31',
    displayName: 'MiG-31BM Foxhound',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'INTERCEPTOR',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'High-altitude performance is OSINT estimate.',
    operatorSummary: 'High-speed interceptor. Mach 2.83, ~1,450km combat radius, Zaslon-AE radar.',
    technicalSpecs: { range: '~3,000km ferry', altitude: '20,600m', radarType: 'Zaslon-AE PESA' },
    tags: ['Russia', 'Interceptor', 'Foxhound'],
  },
  {
    id: 'russia-tu22m3',
    displayName: 'Tu-22M3 Backfire',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'BOMBER',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range and payload are OSINT estimates.',
    operatorSummary: 'Long-range strategic bomber. Kh-22/Kh-32 cruise missiles, ~2,400km combat radius.',
    technicalSpecs: { range: '~6,800km ferry', altitude: '13,300m' },
    tags: ['Russia', 'Bomber', 'Backfire'],
  },
  {
    id: 'russia-a50',
    displayName: 'A-50 Mainstay AEW',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'AEW&C',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Radar performance is OSINT estimate.',
    operatorSummary: 'Russian AEW&C aircraft. Shmel radar, ~400km range, ~6h endurance.',
    technicalSpecs: { range: '~400km', endurance: '~6h', radarType: 'Shmel' },
    tags: ['Russia', 'AEW&C', 'C2'],
  },
  {
    id: 'russia-il20m',
    displayName: 'Il-20M Coot-A (SIGINT)',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SIGINT',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'SIGINT capabilities are not publicly disclosed.',
    operatorSummary: 'Electronic intelligence aircraft. Sensor suite classified, ~6h endurance.',
    technicalSpecs: { range: '~6,500km', endurance: '~6h' },
    tags: ['Russia', 'SIGINT', 'ISR'],
  },

  // ── Russia — GBAD ──────────────────────────────────────────────────────
  {
    id: 'russia-s400',
    displayName: 'S-400 Triumph',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'LONG RANGE SAM',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: 'https://en.wikipedia.org/wiki/S-400_missile_system',
    confidence: 'MEDIUM',
    caveat: 'Range varies by missile type. Pk values are test-condition estimates (low confidence).',
    operatorSummary: 'Mobile long-range SAM system. 4 missile types (40N6E to 9M96E), up to 400km range.',
    technicalSpecs: { range: '400km (40N6E)', altitude: '30km', radarType: '92N6E Grave Stone' },
    tags: ['A2/AD', 'SAM', 'Long Range', 'Russia'],
  },
  {
    id: 'russia-s300v4',
    displayName: 'S-300V4',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'LONG RANGE SAM',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Mobile long-range SAM for army air defense. ~350km range, anti-ballistic capability.',
    technicalSpecs: { range: '~350km', altitude: '~27km' },
    tags: ['Russia', 'SAM', 'Long Range'],
  },
  {
    id: 'russia-pantsir-s1',
    displayName: 'Pantsir-S1',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SHORAD',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range and Pk are OSINT estimates.',
    operatorSummary: 'Gun-missile SHORAD system. 57E6 missiles (~20km), twin 30mm cannons, point defense.',
    technicalSpecs: { range: '~20km', altitude: '~15km' },
    tags: ['Russia', 'SHORAD', 'Point Defense'],
  },
  {
    id: 'russia-tor-m2',
    displayName: 'Tor-M2',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SHORAD',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range is OSINT estimate.',
    operatorSummary: 'Short-range mobile SAM. ~16km range, all-weather, simultaneous 4-target engagement.',
    technicalSpecs: { range: '~16km', altitude: '~10km' },
    tags: ['Russia', 'SHORAD', 'Point Defense'],
  },
  {
    id: 'russia-buk-m3',
    displayName: 'Buk-M3',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'MRAD',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Medium-range mobile SAM. ~70km range, naval and land variants.',
    technicalSpecs: { range: '~70km', altitude: '~25km' },
    tags: ['Russia', 'SAM', 'Medium Range'],
  },

  // ── Russia — Drones & Missiles ──────────────────────────────────────────
  {
    id: 'russia-orlan10',
    displayName: 'Orlan-10',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'ISR DRONE',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'OSINT specifications.',
    operatorSummary: 'Reconnaissance UAV. ~120km range, ~150km/h, ~6,000m ceiling. Used for ISR and targeting.',
    technicalSpecs: { range: '~120km', endurance: '~6h', altitude: '~6,000m' },
    tags: ['Russia', 'Drone', 'ISR'],
  },
  {
    id: 'russia-shahed136',
    displayName: 'Shahed-136',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'KAMIKAZE DRONE',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'OSINT estimates from Ukrainian conflict reporting.',
    operatorSummary: 'Loitering munition / kamikaze drone. ~2,500km range, ~185km/h, ~50kg warhead.',
    technicalSpecs: { range: '~2,500km', endurance: '~12h', altitude: '~4,000m' },
    tags: ['Russia', 'Drone', 'Kamikaze'],
  },
  {
    id: 'russia-geran2',
    displayName: 'Geran-2',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'KAMIKAZE DRONE',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Russian designation for Shahed-136 variant. Same performance envelope.',
    operatorSummary: 'Russian-produced Shahed-136 variant. Same performance characteristics.',
    technicalSpecs: { range: '~2,500km', endurance: '~12h', altitude: '~4,000m' },
    tags: ['Russia', 'Drone', 'Kamikaze'],
  },
  {
    id: 'russia-kalibr',
    displayName: 'Kalibr 3M-14',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'CRUISE MISSILE',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range is OSINT estimate. Exact accuracy is classified.',
    operatorSummary: 'Ship/sub-launched cruise missile. ~1,500-2,500km range, ~925km/h, 450kg warhead.',
    technicalSpecs: { range: '~1,500-2,500km', altitude: '~20-50m terrain following' },
    tags: ['Russia', 'Cruise Missile', 'Kalibr'],
  },
  {
    id: 'russia-iskander',
    displayName: 'Iskander-M (9K720)',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'BALLISTIC MISSILE',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'CEP is disputed. Speed and range are public estimates.',
    operatorSummary: 'Short-range ballistic missile. ~500km range, Mach 6-7, quasi-ballistic trajectory.',
    technicalSpecs: { range: '~500km', altitude: '~50km apogee' },
    tags: ['Russia', 'Ballistic Missile', 'Iskander'],
  },
  {
    id: 'russia-kinzhal',
    displayName: 'Kh-47M2 Kinzhal',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'HYPERSONIC MISSILE',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Speed and range are Russian claims; independent verification is limited.',
    operatorSummary: 'Air-launched hypersonic missile. ~2,000km claimed range, Mach 10 claimed speed.',
    technicalSpecs: { range: '~2,000km (claimed)', altitude: 'Variable' },
    tags: ['Russia', 'Hypersonic', 'Kinzhal'],
  },
  {
    id: 'russia-kh31p',
    displayName: 'Kh-31P (Anti-Radar)',
    side: 'RED',
    layer: 'RUSSIA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'ANTI-RADIATION MISSILE',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'MEDIUM',
    caveat: 'Range is public estimate.',
    operatorSummary: 'Anti-radiation missile for SEAD. ~110km range, Mach 3.5, passive radar seeker.',
    technicalSpecs: { range: '~110km' },
    tags: ['Russia', 'SEAD', 'Anti-Radiation'],
  },

  // ── China — Aircraft ────────────────────────────────────────────────────
  {
    id: 'china-j20',
    displayName: 'J-20 Mighty Dragon',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'STEALTH FIGHTER',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate. Stealth characteristics are not publicly confirmed.',
    operatorSummary: '5th-gen stealth fighter. ~2,000km combat radius (estimated), internal weapon bays.',
    technicalSpecs: { range: '~5,500km ferry', altitude: '~20,000m', radarType: 'Type 1475 KLJ-5 AESA (est.)' },
    tags: ['China', 'Stealth', 'Fighter'],
  },
  {
    id: 'china-j16',
    displayName: 'J-16',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'STRIKE FIGHTER',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: '4.5-gen strike fighter based on Su-30MK2. ~1,500km combat radius (est.), heavy payload.',
    technicalSpecs: { range: '~3,900km ferry', altitude: '~17,000m' },
    tags: ['China', 'Strike', 'Fighter'],
  },
  {
    id: 'china-j10c',
    displayName: 'J-10C',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'MULTIROLE FIGHTER',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: '4.5-gen multirole fighter. AESA radar, PL-15 BVR missiles, ~1,300km combat radius.',
    technicalSpecs: { range: '~3,200km ferry', altitude: '~18,000m', radarType: 'AESA (KLJ-7A est.)' },
    tags: ['China', 'Fighter', 'Multirole'],
  },
  {
    id: 'china-h6k',
    displayName: 'H-6K/N Bomber',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'AIRCRAFT',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'BOMBER',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Combat radius and payload are OSINT estimates.',
    operatorSummary: 'Strategic bomber. CJ-20 cruise missile carrier, ~3,500km combat radius.',
    technicalSpecs: { range: '~9,000km ferry', altitude: '~12,000m' },
    tags: ['China', 'Bomber', 'Strike'],
  },
  {
    id: 'china-kj500',
    displayName: 'KJ-500 AEW',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'C2',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'AEW&C',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Radar range is OSINT estimate.',
    operatorSummary: 'Chinese AEW&C aircraft. ~470km radar range (est.), Y-9 airframe.',
    technicalSpecs: { range: '~470km', endurance: '~8h', radarType: 'Disc AESA (est.)' },
    tags: ['China', 'AEW&C', 'C2'],
  },

  // ── China — GBAD ────────────────────────────────────────────────────────
  {
    id: 'china-hq9b',
    displayName: 'HQ-9B',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'LONG RANGE SAM',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Chinese long-range SAM system. ~300km range (est.), derived from S-300 technology.',
    technicalSpecs: { range: '~300km', altitude: '~27km' },
    tags: ['China', 'SAM', 'Long Range', 'A2/AD'],
  },
  {
    id: 'china-hq22',
    displayName: 'HQ-22',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'MRAD',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Chinese medium-range SAM. ~170km range (est.), solid-fuel missile.',
    technicalSpecs: { range: '~170km', altitude: '~27km' },
    tags: ['China', 'SAM', 'Medium Range'],
  },
  {
    id: 'china-hq17a',
    displayName: 'HQ-17A',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SHORAD',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Chinese short-range mobile SAM. ~20km range, all-weather capability.',
    technicalSpecs: { range: '~20km', altitude: '~10km' },
    tags: ['China', 'SHORAD', 'Point Defense'],
  },
  {
    id: 'china-type625e',
    displayName: 'Type 625E CIWS/SHORAD',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'GBAD',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'CIWS',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Chinese gun-missile CIWS/SHORAD. Gatling gun + short-range missiles, point defense.',
    technicalSpecs: { range: '~3-8km' },
    tags: ['China', 'CIWS', 'Point Defense'],
  },

  // ── China — Drones & Missiles ───────────────────────────────────────────
  {
    id: 'china-wing-loong-ii',
    displayName: 'Wing Loong II',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'MALE UCAV',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is manufacturer claim / OSINT.',
    operatorSummary: 'Medium-altitude long-endurance armed drone. ~1,500km range, 480kg payload.',
    technicalSpecs: { range: '~1,500km', endurance: '~20-32h', altitude: '~9,000m' },
    tags: ['China', 'Drone', 'UCAV'],
  },
  {
    id: 'china-ch4-rainbow',
    displayName: 'CH-4 Rainbow',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'MALE UCAV',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is manufacturer claim.',
    operatorSummary: 'Medium-altitude armed drone. ~3,500km range, 350kg payload, ~30h endurance.',
    technicalSpecs: { range: '~3,500km', endurance: '~30h', altitude: '~7,000m' },
    tags: ['China', 'Drone', 'UCAV'],
  },
  {
    id: 'china-cj100',
    displayName: 'CJ-100 (DF-100)',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'SUPERSONIC CRUISE MISSILE',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Very limited public information.',
    operatorSummary: 'Supersonic cruise missile. Range and speed are disputed.',
    technicalSpecs: { range: 'Disputed' },
    tags: ['China', 'Cruise Missile', 'Supersonic'],
  },
  {
    id: 'china-df21d',
    displayName: 'DF-21D (Anti-Ship Ballistic)',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'ASBM',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'ASBM capability is publicly disputed. Range and accuracy are OSINT estimates.',
    operatorSummary: 'Anti-ship ballistic missile. ~1,500km range (est.), Mach 5+ terminal speed.',
    technicalSpecs: { range: '~1,500km', altitude: '~Ballistic trajectory' },
    tags: ['China', 'ASBM', 'Ballistic'],
  },
  {
    id: 'china-yj18',
    displayName: 'YJ-18 (Anti-Ship Cruise)',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'ANTI-SHIP CRUISE MISSILE',
    publicSourceName: 'OSINT',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Ship-launched anti-ship cruise missile. ~400km range, terminal supersonic speed.',
    technicalSpecs: { range: '~400km' },
    tags: ['China', 'Anti-ship', 'Cruise Missile'],
  },
  {
    id: 'china-df26',
    displayName: 'DF-26 (Intermediate Range)',
    side: 'RED',
    layer: 'CHINA_ARCHETYPE',
    category: 'THREAT_ARCHETYPE',
    mappedTwin: 'ThreatTwin',
    steelAbstraction: 'IRBM',
    publicSourceName: 'OSINT / Public Intelligence',
    publicSourceUrl: '',
    confidence: 'LOW',
    caveat: 'Performance is OSINT estimate.',
    operatorSummary: 'Intermediate-range ballistic missile. ~4,000km range, conventional or nuclear warhead.',
    technicalSpecs: { range: '~4,000km' },
    tags: ['China', 'IRBM', 'Ballistic'],
  },
];