import { REFERENCE_DOCS } from '../../features/reference/reference.manifest';
import {
  NodeCategory,
  PlatformArea,
  TechNode,
} from './knowledge-graph.types';

export const PLATFORM_NODE_CATEGORIES: NodeCategory[] = [
  'CORE',
  'DECISION',
  'LOGISTICS',
  'INTELLIGENCE',
  'GOVERNANCE',
  'SURFACE',
  'DOCUMENTATION',
];

export const PLATFORM_AREAS: PlatformArea[] = [
  'runtime',
  'backend',
  'frontend',
  'docs',
  'research',
  'scaffold',
];

type NodeInit = Omit<TechNode, 'technicalSpecs'> & {
  technicalSpecs?: Partial<TechNode['technicalSpecs']>;
};

function node(def: NodeInit): TechNode {
  return {
    ...def,
    technicalSpecs: {
      inputs: [],
      outputs: [],
      ...def.technicalSpecs,
    },
  };
}

function refDocId(slug: string): string {
  return `REFDOC_${slug.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}`;
}

const CORE_PLATFORM_NODES: TechNode[] = [
  node({
    id: 'PLAT_001',
    label: 'BOREAL_PLATFORM',
    category: 'CORE',
    area: 'scaffold',
    status: 'conceptual',
    description: 'Canonical root for the platform-wide knowledge graph.',
    what: 'A single editorial root that ties the live app, backend seams, docs, and research artifacts together.',
    why: 'Gives the graph one truth-first entry point instead of a set of disconnected feature islands.',
    where: 'Defined in `src/app/core/models/platform-knowledge-graph.data.ts`.',
    who: 'Architects, maintainers, and anyone reading the platform map.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/models/platform-knowledge-graph.data.ts',
    connectedTo: ['RUNTIME_001', 'BACKEND_001', 'DOCS_001', 'RESEARCH_001', 'SCAFFOLD_001', 'KGSA_001'],
    x: 620,
    y: 80,
    z: 0,
    technicalSpecs: {
      logic: 'The graph fans out from this node into runtime, backend, docs, research, and scaffold clusters.',
      verif: 'Manifest sanity check: every cluster is reachable from the root.',
    },
  }),
  node({
    id: 'RUNTIME_001',
    label: 'RUNTIME_SURFACE',
    category: 'SURFACE',
    area: 'runtime',
    status: 'implemented',
    description: 'Live Angular/SSR surfaces that the operator can actually reach.',
    what: 'The shell, navigation, route groups, and in-app decision surfaces.',
    why: 'Represents the visible application layer rather than hidden support code.',
    where: 'Routes, shell, navigation, and route-level feature components in `Steel-Smart-Stridsledning/src/app`.',
    who: 'Commander, tactical operator, analyst, and governance user.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/app.routes.ts',
    connectedTo: ['APP_001', 'NAV_001', 'ROUTES_001', 'OPER_001', 'ANALYTICS_001', 'GOVERNANCE_001', 'STATE_001', 'SERVICES_001', 'KGSA_001'],
    x: 290,
    y: 220,
    z: 0,
    technicalSpecs: {
      inputs: ['route activation', 'signal stores', 'feature flags'],
      outputs: ['operational screens', 'overlay panels', 'decision surfaces'],
    },
  }),
  node({
    id: 'BACKEND_001',
    label: 'BACKEND_SPINE',
    category: 'CORE',
    area: 'backend',
    status: 'partial',
    description: 'Python API, solver, lab, rationale, and WebSocket seams that support the platform.',
    what: 'The backend runtime and ML-adjacent execution spine that sits beside the Angular app.',
    why: 'Holds the parts of the platform that compute, seed, and broadcast state.',
    where: '`api/main.py`, `api/twin_engine.py`, `api/solver.py`, `api/lab.py`, `api/rationale.py`, `api/ws_manager.py`, `api/scenario_seed.py`.',
    who: 'Backend and simulation maintainers.',
    sourcePath: 'api/main.py',
    connectedTo: ['SERVICES_001', 'LABS_001', 'KGSA_001'],
    x: 980,
    y: 220,
    z: 0,
    technicalSpecs: {
      inputs: ['HTTP', 'WebSocket', 'seed state', 'solver requests'],
      outputs: ['campaign snapshots', 'COA solutions', 'lab results', 'rationale text'],
      logic: 'The backend tree is split across API, twin, solver, lab, rationale, and broadcast concerns.',
      verif: 'Presence check: the repo contains the backend files, but integration is still a separate concern.',
    },
  }),
  node({
    id: 'DOCS_001',
    label: 'REFERENCE_DOCS',
    category: 'SURFACE',
    area: 'docs',
    status: 'implemented',
    description: 'Steel reference docs and the truth-first docs shell.',
    what: 'The documentation graph for the Steel app, including the reference shell, manifest, routes, and pages.',
    why: 'Keeps the published docs aligned with the actual repo instead of the aspirational backbone.',
    where: '`Steel-Smart-Stridsledning/src/app/features/reference/*` and `boreal-info-arch/*.md` as source scaffolding.',
    who: 'Documentation readers, reviewers, and maintainers.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/reference/reference.manifest.ts',
    connectedTo: ['REFSHELL_001', 'RESEARCH_001', 'SCAFFOLD_001'],
    x: 290,
    y: 610,
    z: 0,
    technicalSpecs: {
      inputs: ['reference routes', 'repo truth', 'status labels'],
      outputs: ['doc pages', 'source anchors', 'related links'],
    },
  }),
  node({
    id: 'RESEARCH_001',
    label: 'RESEARCH_PACK',
    category: 'INTELLIGENCE',
    area: 'research',
    status: 'implemented',
    description: 'Research notes, build summaries, and design specs that explain the system.',
    what: 'The design and build artifact layer that explains why the platform looks the way it does.',
    why: 'Captures the reasoning behind the platform map and the current build choices.',
    where: '`docs/superpowers/specs/*`, `Steel-Smart-Stridsledning/research/*`, `steel_merged_feature_knowledge_pack/*`.',
    who: 'Product, engineering, and review stakeholders.',
    sourcePath: 'docs/superpowers/specs/2026-04-24-steel-logic-graph-design.md',
    connectedTo: ['DOCS_001', 'SCAFFOLD_001', 'BACKEND_001'],
    x: 980,
    y: 610,
    z: 0,
    technicalSpecs: {
      inputs: ['implementation plans', 'build summaries', 'scoped docs'],
      outputs: ['design rationale', 'knowledge pack', 'scope cuts'],
    },
  }),
  node({
    id: 'SCAFFOLD_001',
    label: 'BOREAL_INFO_ARCH',
    category: 'SURFACE',
    area: 'scaffold',
    status: 'implemented',
    description: 'The scaffold that inspired the broader graph experience.',
    what: 'A parallel knowledge-graph scaffold with its own docs, state, and graph prototype.',
    why: 'Provides the interaction model and structural cue for the platform-wide map.',
    where: '`boreal-info-arch/src/app/features/knowledge-graph/knowledge-graph.ts` and `boreal-info-arch/00-index.md`.',
    who: 'Platform designers and anyone comparing scaffold intent to ship state.',
    sourcePath: 'boreal-info-arch/src/app/features/knowledge-graph/knowledge-graph.ts',
    connectedTo: ['DOCS_001', 'RESEARCH_001', 'KGSA_001'],
    x: 620,
    y: 820,
    z: 0,
    technicalSpecs: {
      inputs: ['scaffold docs', 'knowledge graph prototype', 'domain models'],
      outputs: ['graph interaction model', 'documentation backbone', 'truth-first layout cues'],
    },
  }),
  node({
    id: 'KGSA_001',
    label: 'KNOWLEDGE_GRAPH',
    category: 'INTELLIGENCE',
    area: 'runtime',
    status: 'implemented',
    description: 'The current KGSA route and in-memory graph store.',
    what: 'The in-app situation-awareness graph that now serves as the visible platform map entry point.',
    why: 'Turns the platform-wide manifest into a navigable surface instead of a static document.',
    where: '`/knowledge-graph`, `Steel-Smart-Stridsledning/src/app/features/knowledge-graph.ts`, `Steel-Smart-Stridsledning/src/app/core/state/knowledge-graph.store.ts`, `Steel-Smart-Stridsledning/src/app/core/models/knowledge-graph.types.ts`.',
    who: 'Analysts and users exploring the platform map.',
    route: '/knowledge-graph',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/knowledge-graph.ts',
    connectedTo: ['RUNTIME_001', 'STATE_001', 'DOCS_001', 'SCAFFOLD_001'],
    x: 620,
    y: 430,
    z: 40,
    technicalSpecs: {
      inputs: ['node manifest', 'search query', 'category filters', 'area filters'],
      outputs: ['selected node', 'highlighted edges', 'twin view details'],
    },
  }),
];

const OPERATIONS_NODES: TechNode[] = [
  node({
    id: 'APP_001',
    label: 'APP_SHELL',
    category: 'CORE',
    area: 'runtime',
    status: 'implemented',
    description: 'Angular shell that frames every route.',
    what: 'The root application component, global canvas, and route outlet.',
    why: 'Provides the structural wrapper that makes the app feel like a single system.',
    where: '`Steel-Smart-Stridsledning/src/app/app.ts`, `app.html`, `app.css`.',
    who: 'Every user of the platform.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/app.ts',
    connectedTo: ['NAV_001', 'ROUTES_001', 'OPER_001', 'ANALYTICS_001', 'GOVERNANCE_001'],
    x: 100,
    y: 210,
    z: -20,
  }),
  node({
    id: 'NAV_001',
    label: 'NAV_RAIL',
    category: 'SURFACE',
    area: 'runtime',
    status: 'implemented',
    description: 'Primary navigation chrome and command strip.',
    what: 'The route launcher and context rail at the edge of the app.',
    why: 'Lets the user move between operational, analytical, and governance surfaces.',
    where: '`Steel-Smart-Stridsledning/src/app/shared/ui/nav-rail.ts`, `command-bar.ts`.',
    who: 'Operators and command staff.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/shared/ui/nav-rail.ts',
    connectedTo: ['ROUTES_001', 'OPER_001', 'ANALYTICS_001', 'GOVERNANCE_001', 'KGSA_001', 'SERVICES_001'],
    x: 180,
    y: 330,
    z: -10,
  }),
  node({
    id: 'ROUTES_001',
    label: 'APP_ROUTES',
    category: 'SURFACE',
    area: 'runtime',
    status: 'implemented',
    description: 'Route table for the Steel app.',
    what: 'The canonical route registry that exposes all major feature screens.',
    why: 'Turns the app into a real multi-surface decision environment.',
    where: '`Steel-Smart-Stridsledning/src/app/app.routes.ts`.',
    who: 'Developers and route readers.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/app.routes.ts',
    connectedTo: ['OPER_001', 'ANALYTICS_001', 'GOVERNANCE_001', 'KGSA_001'],
    x: 210,
    y: 450,
    z: -10,
  }),
  node({
    id: 'OPER_001',
    label: 'OPERATIONAL_SURFACES',
    category: 'DECISION',
    area: 'runtime',
    status: 'implemented',
    description: 'Core command surfaces for mission execution.',
    what: 'Overview, tactical, commander, readiness, logistics, and field-facing screens.',
    why: 'Represents the primary route group a user reaches when working the system.',
    where: '`mission-overview.ts`, `tactical-console.ts`, `c2/c2-orchestrator.component.ts`, `readiness-console.ts`, `logistics-console.ts`, `field-console.ts`.',
    who: 'Commander, tactical operator, readiness officer, logistics officer.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/ops/mission-overview.component.ts',
    connectedTo: ['APP_001', 'NAV_001', 'TACT_001', 'CMD_001', 'READ_001', 'LOG_001', 'FIELD_001'],
    x: 360,
    y: 270,
    z: 20,
    technicalSpecs: {
      inputs: ['tracks', 'base readiness', 'policy state', 'supply state'],
      outputs: ['mission overview', 'tactical judgments', 'command actions'],
    },
  }),
  node({
    id: 'ANALYTICS_001',
    label: 'ANALYTIC_LABS',
    category: 'INTELLIGENCE',
    area: 'runtime',
    status: 'partial',
    description: 'Threat, robustness, counterfactual, and resilience analysis surfaces.',
    what: 'Threat inspector, robustness lab, counterfactual lab, C2 resilience lab, drawing board, and demo director.',
    why: 'Lets the user stress the plan, inspect uncertainty, and explore tradeoffs before committing.',
    where: '`threat-inspector.ts`, `lab/robustness-lab.component.ts`, `lab/counterfactual-lab.component.ts`, `lab/c2-resilience-lab.component.ts`, `lab/drawing-board.component.ts`, `demo-director.ts`.',
    who: 'Analyst, red-team cell, and demo operator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/ops/threat-inspector.component.ts',
    connectedTo: ['APP_001', 'NAV_001', 'THR_001', 'ROB_001', 'CF_001', 'C2R_001', 'DRAW_001', 'DEM_001'],
    x: 360,
    y: 590,
    z: 20,
    technicalSpecs: {
      inputs: ['threat tracks', 'policy weights', 'fragility samples', 'counterfactual trials'],
      outputs: ['stress findings', 'rationale', 'projected collapse horizons'],
    },
  }),
  node({
    id: 'GOVERNANCE_001',
    label: 'GOVERNANCE',
    category: 'GOVERNANCE',
    area: 'runtime',
    status: 'implemented',
    description: 'Governance, authority, and audit surfaces.',
    what: 'Governance page, authority dashboard, and audit logger behavior.',
    why: 'Keeps commander decisions traceable and reviewable.',
    where: '`governance.ts`, `c2/authority-dashboard.component.ts`, `audit-logger.ts`.',
    who: 'Governance reviewer and command authority.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/governance.ts',
    connectedTo: ['APP_001', 'NAV_001', 'GOV_001', 'AUTH_001', 'AUD_001', 'POL_001'],
    x: 360,
    y: 760,
    z: 10,
  }),
];

const STATE_AND_SERVICE_NODES: TechNode[] = [
  node({
    id: 'STATE_001',
    label: 'STATE_AND_MODELS',
    category: 'CORE',
    area: 'runtime',
    status: 'partial',
    description: 'Signal stores and shared models that feed the surfaces.',
    what: 'Policy, decision fabric, KGSA, sensor feed, map layer, lab, orchestration, and capability state.',
    why: 'Provides the reactive data backbone the screens and services consume.',
    where: '`core/state/*`, `core/models/*`, and `shared/domain/*`.',
    who: 'Frontend and platform maintainers.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/state/policy.store.ts',
    connectedTo: ['POL_001', 'FAB_001', 'KGSA_001', 'SENS_001', 'MAP_001', 'LABS_001', 'SERVICES_001', 'C2R_001'],
    x: 250,
    y: 870,
    z: 0,
    technicalSpecs: {
      inputs: ['route interactions', 'sensor streams', 'policy changes', 'orchestration triggers'],
      outputs: ['selected COA', 'graph state', 'sensor state', 'resilience score'],
    },
  }),
  node({
    id: 'SERVICES_001',
    label: 'SERVICE_LAYER',
    category: 'DECISION',
    area: 'runtime',
    status: 'partial',
    description: 'Client services that bridge UI, backend, and local heuristics.',
    what: 'SSS API, Steel API, LLM, intent estimation, theater WebSocket, sensor adapters, capability orchestration, and feature flags.',
    why: 'Concentrates the non-view logic that binds the app to runtime data and external seams.',
    where: '`core/services/*`.',
    who: 'Frontend engineers and integrators.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/services/steel-api.service.ts',
    connectedTo: ['SSSAPI_001', 'STEELAPI_001', 'LLM_001', 'INTENT_001', 'THEATERWS_001', 'SENSORADAPTER_001', 'CAPORCH_001', 'FLAGS_001', 'BACKEND_001'],
    x: 520,
    y: 250,
    z: 30,
    technicalSpecs: {
      inputs: ['HTTP', 'WebSocket', 'signals', 'feature state'],
      outputs: ['API results', 'intent scores', 'broadcast frames', 'feature gates'],
    },
  }),
  node({
    id: 'POL_001',
    label: 'POLICY_AND_SOLVER',
    category: 'DECISION',
    area: 'runtime',
    status: 'implemented',
    description: 'Policy weights and COA solving behavior.',
    what: 'The policy store, guardrails, and COA solve trigger path.',
    why: 'Lets the commander tune the trade space between safety, sustainability, and resilience.',
    where: '`core/state/policy.store.ts`, `shared/domain/models.ts`, `core/services/steel-api.service.ts`.',
    who: 'Commander and policy staff.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/state/policy.store.ts',
    connectedTo: ['STATE_001', 'SERVICES_001', 'BACKEND_001', 'C2R_001', 'GOVERNANCE_001'],
    x: 460,
    y: 980,
    z: 20,
    technicalSpecs: {
      inputs: ['weights', 'guardrails', 'readiness floors'],
      outputs: ['COA requests', 'selected COA', 'policy audit log'],
      logic: 'A debounced solve cycle re-runs when policy weights change.',
    },
  }),
  node({
    id: 'FAB_001',
    label: 'DECISION_FABRIC',
    category: 'CORE',
    area: 'runtime',
    status: 'implemented',
    description: 'The command-friction model that projects resilience.',
    what: 'Decision fabric state plus the command friction engine that derives resilience and collapse horizons.',
    why: 'Shows whether the operating concept still holds under pressure.',
    where: '`core/state/decision-fabric.store.ts`, `core/sim/command-friction-engine.ts`.',
    who: 'Commanders and governance reviewers.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/state/decision-fabric.store.ts',
    connectedTo: ['STATE_001', 'C2R_001', 'GOVERNANCE_001', 'BACKEND_001'],
    x: 620,
    y: 980,
    z: 10,
    technicalSpecs: {
      inputs: ['tracks', 'policy authority', 'logistics health', 'lab failure probability'],
      outputs: ['resilience score', 'collapse horizon', 'friction status'],
    },
  }),
  node({
    id: 'SENS_001',
    label: 'SENSOR_FEED',
    category: 'SURFACE',
    area: 'runtime',
    status: 'partial',
    description: 'Sensor feed, replay, and adapter coordination.',
    what: 'The live/mock/replay sensor feed layer and the adapter service behind it.',
    why: 'Keeps the tactical picture responsive without hard-coding a single input mode.',
    where: '`core/state/sensor-feed.store.ts`, `core/services/sensor-adapter.ts`, `core/services/theater-ws.service.ts`.',
    who: 'Tactical operator and platform integrator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/state/sensor-feed.store.ts',
    connectedTo: ['STATE_001', 'SERVICES_001', 'TACT_001', 'THR_001', 'BACKEND_001'],
    x: 100,
    y: 980,
    z: 10,
    technicalSpecs: {
      inputs: ['live feed', 'replay feed', 'synthetic feed'],
      outputs: ['track deltas', 'sensor state', 'timing updates'],
    },
  }),
  node({
    id: 'MAP_001',
    label: 'MAP_LAYER',
    category: 'SURFACE',
    area: 'runtime',
    status: 'implemented',
    description: 'Map and rendering state for spatial surfaces.',
    what: 'The map layer store and related spatial rendering state.',
    why: 'Keeps tactical and logistics views aligned to the same spatial frame.',
    where: '`core/state/map-layer.store.ts`, `shared/domain/engagement-map.data.ts`.',
    who: 'Tactical operator and analyst.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/state/map-layer.store.ts',
    connectedTo: ['STATE_001', 'OPER_001', 'LOG_001', 'FIELD_001'],
    x: 100,
    y: 1130,
    z: 0,
  }),
  node({
    id: 'LABS_001',
    label: 'LAB_STATE',
    category: 'INTELLIGENCE',
    area: 'runtime',
    status: 'partial',
    description: 'Lab store and other analytical state surfaces.',
    what: 'Robustness, counterfactual, and lab-state data that backs the analytical routes.',
    why: 'Preserves experiment results and red-team findings across the app.',
    where: '`core/state/lab.store.ts`, `core/ml/counterfactual-lab.store.ts`, `features/lab/robustness-lab.component.ts`, `features/lab/counterfactual-lab.component.ts`.',
    who: 'Analyst and red-team cell.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/core/state/lab.store.ts',
    connectedTo: ['STATE_001', 'ANALYTICS_001', 'BACKEND_001'],
    x: 460,
    y: 1130,
    z: 0,
  }),
];

const ANALYTICAL_AND_ROUTE_NODES: TechNode[] = [
  node({
    id: 'TACT_001',
    label: 'TACTICAL_CONSOLE',
    category: 'DECISION',
    area: 'runtime',
    status: 'implemented',
    description: 'The tactical picture and engagement surface.',
    what: 'The tactical console, threat view, and engagement reasoning path.',
    why: 'Lets operators inspect tracks and make defensive decisions in context.',
    where: '`features/tactical-console.ts`, `features/threat-inspector.ts`, `core/state/tactical.store.ts`.',
    who: 'Tactical operator and air-defense coordinator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/ops/tactical-console.component.ts',
    connectedTo: ['OPER_001', 'SENS_001', 'POL_001', 'KGSA_001', 'THR_001'],
    x: 470,
    y: 330,
    z: 40,
  }),
  node({
    id: 'CMD_001',
    label: 'COMMANDER_ORCHESTRATOR',
    category: 'DECISION',
    area: 'runtime',
    status: 'implemented',
    description: 'Commander view and policy panel.',
    what: 'The commander orchestrator, header, frontier, outcome, and policy panels.',
    why: 'Makes the policy trade-offs explicit before a decision is locked in.',
    where: '`features/c2/c2-orchestrator.component.ts`, `commander-header-panel.ts`, `commander-frontier-panel.ts`, `commander-outcome-panel.ts`, `commander-policy-panel.ts`.',
    who: 'Commander and decision authority.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/c2/c2-orchestrator.component.ts',
    connectedTo: ['OPER_001', 'POL_001', 'GOVERNANCE_001', 'FAB_001'],
    x: 620,
    y: 330,
    z: 30,
  }),
  node({
    id: 'READ_001',
    label: 'READINESS_CONSOLE',
    category: 'CORE',
    area: 'runtime',
    status: 'implemented',
    description: 'Base readiness and sustainment surface.',
    what: 'The readiness console and projection logic for blue-force bases.',
    why: 'Shows the second-order effects of engaging now versus holding reserve.',
    where: '`features/lab/readiness-console.component.ts`, `core/state/readiness.store.ts`, `shared/domain/models.ts`.',
    who: 'Readiness officer and commander.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/lab/readiness-console.component.ts',
    connectedTo: ['OPER_001', 'LOG_001', 'POL_001', 'FAB_001'],
    x: 770,
    y: 330,
    z: 20,
  }),
  node({
    id: 'LOG_001',
    label: 'LOGISTICS_CONSOLE',
    category: 'LOGISTICS',
    area: 'runtime',
    status: 'implemented',
    description: 'Supply, sustainment, and logistics view.',
    what: 'The logistics console and sustainment model.',
    why: 'Keeps ammunition, fuel, and corridor health visible while planning decisions.',
    where: '`features/logistics-console.ts`, `core/state/logistics.store.ts`, `shared/domain/logistics-ontology.ts`.',
    who: 'Logistics officer.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/ops/logistics-console.component.ts',
    connectedTo: ['OPER_001', 'READ_001', 'MAP_001', 'FAB_001'],
    x: 920,
    y: 330,
    z: 20,
  }),
  node({
    id: 'FIELD_001',
    label: 'FIELD_CONSOLE',
    category: 'SURFACE',
    area: 'runtime',
    status: 'implemented',
    description: 'Field-facing mobile command surface.',
    what: 'The field terminal and its operator-specific surface.',
    why: 'Represents the lower-friction on-the-move view of the platform.',
    where: '`features/field-console.ts`.',
    who: 'Field operator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/ops/field-console.component.ts',
    connectedTo: ['OPER_001', 'MAP_001', 'SENS_001'],
    x: 1080,
    y: 330,
    z: 10,
  }),
  node({
    id: 'THR_001',
    label: 'THREAT_INSPECTOR',
    category: 'INTELLIGENCE',
    area: 'runtime',
    status: 'implemented',
    description: 'Threat assessment and intent inspection surface.',
    what: 'The threat inspector route and its intent-estimation helpers.',
    why: 'Lets analysts read signal quality and intent uncertainty before recommending action.',
    where: '`features/threat-inspector.ts`, `core/services/intent-estimator.service.ts`.',
    who: 'Analyst and tactical operator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/ops/threat-inspector.component.ts',
    connectedTo: ['ANALYTICS_001', 'TACT_001', 'SENS_001', 'KGSA_001'],
    x: 470,
    y: 740,
    z: 40,
  }),
  node({
    id: 'ROB_001',
    label: 'ROBUSTNESS_LAB',
    category: 'INTELLIGENCE',
    area: 'runtime',
    status: 'implemented',
    description: 'Robustness stress-testing surface.',
    what: 'The robustness lab and its stress-running heuristics.',
    why: 'Tests whether the plan survives saturation, deception, and degradation.',
    where: '`features/lab/robustness-lab.component.ts`, `core/state/lab.store.ts`, `core/sim/command-friction-engine.ts`.',
    who: 'Analyst and red-team cell.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/lab/robustness-lab.component.ts',
    connectedTo: ['ANALYTICS_001', 'LABS_001', 'BACKEND_001'],
    x: 620,
    y: 740,
    z: 30,
  }),
  node({
    id: 'CF_001',
    label: 'COUNTERFACTUAL_LAB',
    category: 'INTELLIGENCE',
    area: 'runtime',
    status: 'partial',
    description: 'Counterfactual command and ML trial surface.',
    what: 'The counterfactual lab and its local ML state.',
    why: 'Explores how policy perturbations change projected outcomes.',
    where: '`features/lab/counterfactual-lab.component.ts`, `core/ml/counterfactual-lab.store.ts`, `api/ml/*`, `scripts/ml/*`.',
    who: 'Analyst and machine-learning operator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/lab/counterfactual-lab.component.ts',
    connectedTo: ['ANALYTICS_001', 'LABS_001', 'BACKEND_001', 'SERVICES_001'],
    x: 770,
    y: 740,
    z: 20,
  }),
  node({
    id: 'DRAW_001',
    label: 'DRAWING_BOARD',
    category: 'DECISION',
    area: 'runtime',
    status: 'implemented',
    description: 'Interactive tactical sketching surface with dual-path simulation (Simple vs. Advanced).',
    what: 'The drawing board where users sketch unit trajectories and see them play out via heuristics or doctrinal forests.',
    why: 'Enables rapid operational sketching and high-fidelity doctrinal what-if analysis.',
    where: '`features/lab/drawing-board.component.ts`, `core/state/drawing-board.store.ts`.',
    who: 'Tactical analyst and red-team operator.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/lab/drawing-board.component.ts',
    connectedTo: ['ANALYTICS_001', 'ML_FOREST_001', 'VAULT_001', 'MAP_001'],
    x: 470,
    y: 870,
    z: 30,
    technicalSpecs: {
      inputs: ['pointer events', 'waypoint signals', 'advanced sim results'],
      outputs: ['unit sketches', 'interceptor lines', 'conflict markers'],
    },
  }),
  node({
    id: 'ML_FOREST_001',
    label: 'DOCTRINAL_FOREST',
    category: 'INTELLIGENCE',
    area: 'backend',
    status: 'implemented',
    description: 'Ensemble of decision trees grounded in Swedish functional ontology.',
    what: 'A NumPy-based random forest that predicts trajectories and reactions based on base roles and fatigue.',
    why: 'Enables advanced "what-if" simulations that respect military doctrine.',
    where: '`api/ml/inference.py`.',
    who: 'ML maintainers and doctrinal analysts.',
    sourcePath: 'api/ml/inference.py',
    connectedTo: ['API_MAIN_001', 'API_LAB_001', 'DRAW_001'],
    x: 750,
    y: 280,
    z: 40,
    technicalSpecs: {
      inputs: ['unit sketches', 'base fatigue', 'policy weights'],
      outputs: ['ScenarioBundle', 'predicted trajectories', 'conflict nodes'],
      logic: 'Splits on ontology properties like base_role and crew_fatigue.',
    },
  }),
  node({
    id: 'VAULT_001',
    label: 'SCENARIO_VAULT',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'JSON-based scenario persistence layer.',
    what: 'Backend endpoints and file storage for saving/loading tactical situations.',
    why: 'Allows users to preserve and share complex "what-if" scenarios.',
    where: '`api/main.py` and `api/data/scenarios.json`.',
    who: 'Platform users.',
    sourcePath: 'api/main.py',
    connectedTo: ['API_MAIN_001', 'DRAW_001'],
    x: 1180,
    y: 820,
    z: 10,
    technicalSpecs: {
      inputs: ['ScenarioState JSON'],
      outputs: ['saved scenario IDs', 'scenario list'],
    },
  }),
  node({
    id: 'C2R_001',
    label: 'C2_RESILIENCE',
    category: 'DECISION',
    area: 'runtime',
    status: 'implemented',
    description: 'Resilience projection and collapse horizon surface.',
    what: 'The C2 resilience lab and the command-friction scoring model.',
    why: 'Shows whether the system can keep functioning under load and uncertainty.',
    where: '`features/c2-resilience-lab.ts`, `core/state/decision-fabric.store.ts`, `core/sim/command-friction-engine.ts`.',
    who: 'Commander, governance reviewer, and analyst.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/c2-resilience-lab.ts',
    connectedTo: ['ANALYTICS_001', 'FAB_001', 'POL_001', 'GOVERNANCE_001'],
    x: 920,
    y: 740,
    z: 30,
  }),
  node({
    id: 'DEM_001',
    label: 'DEMO_DIRECTOR',
    category: 'SURFACE',
    area: 'runtime',
    status: 'implemented',
    description: 'Demo orchestration and scenario injection surface.',
    what: 'The operator that seeds or steers demonstration scenarios.',
    why: 'Makes the graph useful in live walkthroughs and feature demos.',
    where: '`features/demo-director.ts`.',
    who: 'Demo operator and presenter.',
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/demo-director.ts',
    connectedTo: ['ANALYTICS_001', 'OPER_001', 'SENS_001', 'BACKEND_001'],
    x: 1080,
    y: 740,
    z: 10,
  }),
];

const BACKEND_DETAIL_NODES: TechNode[] = [
  node({
    id: 'API_MAIN_001',
    label: 'API_MAIN',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'FastAPI application entrypoint.',
    what: 'The backend application bootstrap and route registration point.',
    why: 'Provides the server root for the computational and broadcast seams.',
    where: '`api/main.py` and `api/__init__.py`.',
    who: 'Backend maintainers.',
    sourcePath: 'api/main.py',
    connectedTo: ['BACKEND_001', 'API_TWIN_001', 'API_SOLVER_001', 'API_LAB_001', 'API_RATIONALE_001', 'API_WS_001', 'FASTAPI_001'],
    x: 820,
    y: 430,
    z: 20,
  }),
  node({
    id: 'FASTAPI_001',
    label: 'FASTAPI_BACKEND',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'Python REST/WS application server routing authoritative commands and models.',
    what: 'The Python FastAPI backend that serves as the single source of truth for decision logic.',
    why: 'Moves domain authority from the client to a scalable, high-performance Python environment.',
    where: '`api/main.py` and the `api/` directory.',
    who: 'Architects and backend maintainers.',
    sourcePath: 'api/main.py',
    connectedTo: ['API_MAIN_001', 'WS_001', 'ML_001', 'RPA_001', 'SERVICES_001'],
    x: 750,
    y: 350,
    z: 50,
    technicalSpecs: {
      inputs: ['HTTP_REQ', 'WS_MSG', 'STATE_VECTOR'],
      outputs: ['JSON_RES', 'WS_BROADCAST', 'ML_PREDICTIONS'],
    },
  }),
  node({
    id: 'WS_001',
    label: 'WEBSOCKET_MANAGER',
    category: 'SURFACE',
    area: 'backend',
    status: 'implemented',
    description: 'Handles live high-frequency theater state deltas between Engine and UI.',
    what: 'The server-side broadcast manager for theater updates.',
    why: 'Ensures all connected clients see the same synchronized tactical picture.',
    where: '`api/ws_manager.py`.',
    who: 'Platform integrators.',
    sourcePath: 'api/ws_manager.py',
    connectedTo: ['FASTAPI_001', 'API_TWIN_001', 'THEATERWS_001'],
    x: 600,
    y: 300,
    z: 40,
  }),
  node({
    id: 'ML_001',
    label: 'ENSEMBLE_INFERENCE',
    category: 'INTELLIGENCE',
    area: 'backend',
    status: 'implemented',
    description: 'Local fast-path LightGBM quantile regressor ensemble.',
    what: 'Predictive model for track trajectories and trust scoring.',
    why: 'Provides sub-millisecond counterfactual predictions when the simulation is under load.',
    where: '`api/ml/inference.py`.',
    who: 'ML engineers.',
    sourcePath: 'api/ml/inference.py',
    connectedTo: ['FASTAPI_001', 'RPA_001', 'CF_001'],
    x: 900,
    y: 300,
    z: 40,
    technicalSpecs: {
      math: 'Variance between 5 LightGBM models = Trust',
    },
  }),
  node({
    id: 'RPA_001',
    label: 'RUNPOD_ORCHESTRATOR',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'Dispatches deep simulations to spot GPUs when ML trust is low.',
    what: 'Serverless GPU worker orchestration for high-fidelity simulation.',
    why: 'Provides a massive compute burst when local models cannot resolve uncertainty.',
    where: '`api/ml/runpod_client.py`.',
    who: 'Infrastructure and ML engineers.',
    sourcePath: 'api/ml/runpod_client.py',
    connectedTo: ['FASTAPI_001', 'ML_001', 'AUD_001'],
    x: 1050,
    y: 350,
    z: 30,
  }),
  node({
    id: 'REPLAY_001',
    label: 'REPLAY_REGISTRY',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'Idempotent registry for operational directive synchronization.',
    what: 'Handles deduplication and persistence of replayed client actions.',
    why: 'Ensures that commands issued during offline or high-latency periods are only applied once.',
    where: '`api/replay.py`.',
    who: 'Backend engineers and platform integrators.',
    sourcePath: 'api/replay.py',
    connectedTo: ['FASTAPI_001', 'SERVICES_001'],
    x: 1150,
    y: 250,
    z: 20,
    technicalSpecs: {
      inputs: ['clientActionId', 'queuedAt'],
      outputs: ['accepted/replayed status', 'echoed payload'],
      verif: 'Idempotency test suite',
    },
  }),
  node({
    id: 'API_TWIN_001',
    label: 'TWIN_ENGINE',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'Digital twin state engine.',
    what: 'The backend twin model and state evolution layer.',
    why: 'Keeps the operational snapshot coherent across ticks.',
    where: '`api/twin_engine.py`.',
    who: 'Backend and simulation maintainers.',
    sourcePath: 'api/twin_engine.py',
    connectedTo: ['API_MAIN_001', 'API_SOLVER_001', 'API_SEED_001'],
    x: 1000,
    y: 430,
    z: 30,
  }),
  node({
    id: 'API_SOLVER_001',
    label: 'COA_SOLVER',
    category: 'DECISION',
    area: 'backend',
    status: 'implemented',
    description: 'Policy-weighted COA solver and reachability filter.',
    what: 'The backend solver that scores and selects candidate courses of action.',
    why: 'Converts policy weight changes into ranked plans.',
    where: '`api/solver.py`.',
    who: 'Backend and decision-support maintainers.',
    sourcePath: 'api/solver.py',
    connectedTo: ['API_MAIN_001', 'API_TWIN_001', 'API_LAB_001'],
    x: 1180,
    y: 430,
    z: 20,
  }),
  node({
    id: 'API_LAB_001',
    label: 'MONTE_CARLO_LAB',
    category: 'INTELLIGENCE',
    area: 'backend',
    status: 'implemented',
    description: 'Stochastic stress-test engine.',
    what: 'The backend lab that executes Monte Carlo-style robustness runs.',
    why: 'Quantifies how the plan behaves under red-force perturbations.',
    where: '`api/lab.py`.',
    who: 'Analyst and red-team operator.',
    sourcePath: 'api/lab.py',
    connectedTo: ['API_MAIN_001', 'API_SOLVER_001', 'API_RATIONALE_001'],
    x: 840,
    y: 560,
    z: 20,
  }),
  node({
    id: 'API_RATIONALE_001',
    label: 'RATIONALE',
    category: 'GOVERNANCE',
    area: 'backend',
    status: 'partial',
    description: 'LLM-backed rationale generation seam.',
    what: 'The backend rationale generator for explanations and summaries.',
    why: 'Turns solved outputs into plain-language decision support.',
    where: '`api/rationale.py`.',
    who: 'Commander and governance reviewer.',
    sourcePath: 'api/rationale.py',
    connectedTo: ['API_MAIN_001', 'API_LAB_001', 'BACKEND_001'],
    x: 1000,
    y: 560,
    z: 20,
  }),
  node({
    id: 'API_WS_001',
    label: 'WS_MANAGER',
    category: 'SURFACE',
    area: 'backend',
    status: 'implemented',
    description: 'WebSocket manager for live state broadcasts.',
    what: 'The server-side broadcast manager for theater updates.',
    why: 'Keeps the live display synchronized with the backend snapshot.',
    where: '`api/ws_manager.py`.',
    who: 'Platform integrator.',
    sourcePath: 'api/ws_manager.py',
    connectedTo: ['API_MAIN_001', 'API_TWIN_001', 'SENS_001'],
    x: 1180,
    y: 560,
    z: 10,
  }),
  node({
    id: 'API_SEED_001',
    label: 'SCENARIO_SEED',
    category: 'SURFACE',
    area: 'backend',
    status: 'implemented',
    description: 'Scenario seed and initial state builder.',
    what: 'The seed logic that initializes the campaign and scenario baseline.',
    why: 'Makes the backend deterministic enough to start from a known state.',
    where: '`api/scenario_seed.py`.',
    who: 'Simulation maintainers.',
    sourcePath: 'api/scenario_seed.py',
    connectedTo: ['API_TWIN_001', 'RESEARCH_001'],
    x: 1000,
    y: 690,
    z: 10,
  }),
  node({
    id: 'API_MODELS_001',
    label: 'API_MODELS',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'Typed request and response models.',
    what: 'The Pydantic schema layer for backend I/O.',
    why: 'Prevents the backend contract from drifting away from the UI expectations.',
    where: '`api/models.py` and `api/ml/models.py`.',
    who: 'Backend and frontend integrators.',
    sourcePath: 'api/models.py',
    connectedTo: ['API_MAIN_001', 'SERVICES_001'],
    x: 1180,
    y: 690,
    z: 10,
  }),
  node({
    id: 'SCRIPT_ML_001',
    label: 'ML_SCRIPTS',
    category: 'INTELLIGENCE',
    area: 'backend',
    status: 'implemented',
    description: 'Training and preemption-handling scripts.',
    what: 'The ML worker scripts used to train, clean up, and manage offline jobs.',
    why: 'Explains the offline side of the platform beyond the HTTP API.',
    where: '`scripts/ml/train_worker.py`, `scripts/ml/cleanup_preempted.py`, `scripts/ml/test_train_worker.py`, `scripts/ml/test_cleanup.py`.',
    who: 'ML and automation maintainers.',
    sourcePath: 'scripts/ml/train_worker.py',
    connectedTo: ['API_LAB_001', 'RESEARCH_001'],
    x: 840,
    y: 690,
    z: 10,
  }),
];

const RESEARCH_PACK_NODES: TechNode[] = [
  node({
    id: 'PACK_001',
    label: 'FEATURE_KNOWLEDGE_PACK',
    category: 'SURFACE',
    area: 'research',
    status: 'implemented',
    description: 'Merged feature knowledge pack used as a repo truth source.',
    what: 'The consolidated feature and domain pack that informs the graph scope.',
    why: 'Provides a prior scaffold for the current implementation narrative.',
    where: '`steel_merged_feature_knowledge_pack/*`.',
    who: 'Technical documentation readers.',
    sourcePath: 'steel_merged_feature_knowledge_pack/00-index.md',
    connectedTo: ['RESEARCH_001', 'DOCS_001'],
    x: 860,
    y: 820,
    z: 10,
  }),
  node({
    id: 'PLAN_001',
    label: 'IMPLEMENTATION_PLAN',
    category: 'DECISION',
    area: 'research',
    status: 'implemented',
    description: 'Plan describing the backend/twin sprint.',
    what: 'The pre-hackathon implementation plan that explains the intended build sequence.',
    why: 'Shows the decision flow that shaped the platform seams.',
    where: '`Steel-Smart-Stridsledning/research/SSS_Implementation_Plan_22Apr2026.md`.',
    who: 'Engineers and reviewers.',
    sourcePath: 'Steel-Smart-Stridsledning/research/SSS_Implementation_Plan_22Apr2026.md',
    connectedTo: ['RESEARCH_001', 'BACKEND_001'],
    x: 1040,
    y: 820,
    z: 10,
  }),
  node({
    id: 'BUILD_001',
    label: 'BUILD_SUMMARY',
    category: 'CORE',
    area: 'research',
    status: 'implemented',
    description: 'Build summary of the full-stack sprint.',
    what: 'The build summary that records what was wired during the sprint.',
    why: 'Documents the current technical truth before the next cutover.',
    where: '`Steel-Smart-Stridsledning/research/SSS_Build_Summary_23Apr2026.md`.',
    who: 'Engineers and maintainers.',
    sourcePath: 'Steel-Smart-Stridsledning/research/SSS_Build_Summary_23Apr2026.md',
    connectedTo: ['RESEARCH_001', 'BACKEND_001', 'RUNTIME_001'],
    x: 860,
    y: 980,
    z: 10,
  }),
  node({
    id: 'SPEC_001',
    label: 'LOGIC_GRAPH_SPEC',
    category: 'INTELLIGENCE',
    area: 'research',
    status: 'implemented',
    description: 'Logic-graph design spec for the scaffold itself.',
    what: 'The design spec that describes the scaffold-style graph model and its interaction rules.',
    why: 'Connects the platform map back to the blueprint that inspired it.',
    where: '`docs/superpowers/specs/2026-04-24-steel-logic-graph-design.md`.',
    who: 'Design reviewers and engineers.',
    sourcePath: 'docs/superpowers/specs/2026-04-24-steel-logic-graph-design.md',
    connectedTo: ['RESEARCH_001', 'SCAFFOLD_001'],
    x: 1040,
    y: 980,
    z: 10,
  }),
  node({
    id: 'MATH_001',
    label: 'LOGISTIC_COGNITIVE_LOAD',
    category: 'CORE',
    area: 'backend',
    status: 'implemented',
    description: 'S-Curve model for operator exhaustion.',
    what: 'Replaces linear load degradation with logistic functions.',
    why: 'Simulates true human breaking points.',
    sourcePath: 'api/decision_fabric.py',
    connectedTo: ['API_TWIN_001', 'SOURCE_NATO_001'],
    x: 800, y: 800, z: 10,
  }),
  node({
    id: 'MATH_002',
    label: 'SPATIAL_CLUSTER_DENSITY',
    category: 'INTELLIGENCE',
    area: 'backend',
    status: 'implemented',
    description: 'Calculates threat density using spatial Convex Hull.',
    what: 'Replaces simple track counting with spatial volume tracking.',
    why: 'Identifies adversarial swarms dynamically.',
    sourcePath: 'api/main.py',
    connectedTo: ['FASTAPI_001', 'ML_001'],
    x: 850, y: 750, z: 15,
  }),
  node({
    id: 'MATH_003',
    label: 'ADVERSARIAL_INTENT_ESTIMATION',
    category: 'INTELLIGENCE',
    area: 'backend',
    status: 'implemented',
    description: 'Probabilistic intent model for adversarial agents drawn on the map.',
    what: 'Infers hidden objectives from kinematic track features and behavior.',
    why: 'Enables proactive defense rather than reactive interception.',
    sourcePath: 'api/ml/inference.py',
    connectedTo: ['MATH_002', 'ML_001', 'THR_001'],
    x: 880, y: 700, z: 20,
  }),
  node({
    id: 'SOURCE_NATO_001',
    label: 'NATO_DATA_CENTRICITY',
    category: 'SURFACE',
    area: 'frontend',
    status: 'conceptual',
    description: 'NATO Strategic Concepts for Data-Centric Warfighting.',
    what: 'The strategic intent behind BDT.',
    why: 'Aligns the application with actual strategic goals.',
    sourcePath: 'https://www.act.nato.int/article/data-centricity/',
    connectedTo: ['MATH_001'],
    x: 950, y: 800, z: 5,
  }),
  node({
    id: 'SOURCE_SAAB_001',
    label: 'SAAB_C2_SYSTEMS',
    category: 'SURFACE',
    area: 'frontend',
    status: 'implemented',
    description: 'Command and Control Product Specifications.',
    what: 'The public specs driving the Capability Layer.',
    why: 'Grounds the simulation in physical reality.',
    sourcePath: 'https://www.saab.com/products/air/command-and-control',
    connectedTo: ['MATH_002'],
    x: 900, y: 850, z: 5,
  }),
];

const REFERENCE_DOC_NODES: TechNode[] = REFERENCE_DOCS.map((doc, index, docs) =>
  node({
    id: refDocId(doc.slug),
    label: `${doc.order.toString().padStart(2, '0')}_${doc.slug.replace(/^\d+-/, '').replace(/-/g, '_').toUpperCase()}`,
    category: 'DOCUMENTATION',
    area: 'docs',
    status: doc.status,
    description: doc.summary,
    what: doc.title,
    why: doc.summary,
    where: `${doc.route} and ` +
      `Steel-Smart-Stridsledning/src/app/features/reference/reference.manifest.ts`,
    who: 'Documentation readers and maintainers.',
    route: doc.route,
    sourcePath: 'Steel-Smart-Stridsledning/src/app/features/reference/reference.manifest.ts',
    connectedTo: [
      'DOCS_001',
      index < docs.length - 1 ? refDocId(docs[index + 1].slug) : '',
    ].filter(Boolean) as string[],
    x: 1290,
    y: 150 + (index * 78),
    z: 0,
    technicalSpecs: {
      inputs: ['reference manifest', 'route metadata', 'doc text'],
      outputs: ['truth-first docs page', 'source anchors', 'related links'],
    },
  })
);

export const PLATFORM_KNOWLEDGE_GRAPH_NODES: TechNode[] = [
  ...CORE_PLATFORM_NODES,
  ...OPERATIONS_NODES,
  ...STATE_AND_SERVICE_NODES,
  ...ANALYTICAL_AND_ROUTE_NODES,
  ...BACKEND_DETAIL_NODES,
  ...RESEARCH_PACK_NODES,
  ...REFERENCE_DOC_NODES,
];

export function getPlatformNodeById(id: string): TechNode | null {
  return PLATFORM_KNOWLEDGE_GRAPH_NODES.find(node => node.id === id) ?? null;
}
